### ISSUE TITLE
User-agent of Quest

### ISSUE THREAD

**Issue by willwac** [oeed/Quest#2]
What is Quest's user agent?
I would like to make a site that returns a quest friendly version if on quest and a regular desktop version if using a desktop browser.

**Comment by cpixelcube** [comment]
I'm very late, but here's another way you can detect that:
```
function isCCML() {
    if (!isset($_POST['questClientIdentifier'])) {
        //CCML   
        return true;
    } else {
        //HTML
        return false;
    }
}
```
